### Setup

In [28]:
import os
import json
import random
import time
import requests
from bs4 import BeautifulSoup
import snowflake.connector
import pandas as pd
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

conn = snowflake.connector.connect(
    account=os.getenv("SNOWFLAKE_ACCOUNT"),
    user=os.getenv("SNOWFLAKE_USER"),
    password=os.getenv("SNOWFLAKE_PASSWORD"),
    role=os.getenv("SNOWFLAKE_ROLE"),
    warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
    database="RAW",
)

def run_query(sql):
    cur = conn.cursor()
    cur.execute(sql)
    rows = cur.fetchall()
    cols = [desc[0] for desc in cur.description]
    cur.close()
    return pd.DataFrame(rows, columns=cols)

HEADERS = {
    "User-Agent":      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                       "AppleWebKit/537.36 (KHTML, like Gecko) "
                       "Chrome/122.0.0.0 Safari/537.36",
    "Accept":          "text/html,application/xhtml+xml,application/xml;"
                       "q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer":         "https://www.builtinnyc.com/",
}
MIN_SCRAPE_DELAY = 8.0
MAX_SCRAPE_DELAY = 15.0
KNOWN_SENIORITY_VALUES = {"Entry level", "Junior", "Mid level"}

print("Setup OK")

Setup OK

### Fetch candidates

In [29]:
candidates = run_query("""
    SELECT
        RAW_PAYLOAD:source_url::STRING as source_url,
        RAW_PAYLOAD:crawl_title::STRING as title
    FROM RAW.BUILTIN.SRC_POSTINGS
    WHERE RAW_PAYLOAD:seniority::STRING IS NULL
    ORDER BY INGESTED_AT DESC
""")

print(f"Candidates to backfill: {len(candidates)}")
display(candidates)

Candidates to backfill: 50

,SOURCE_URL,TITLE
0,https://www.builtinnyc.com/job/data-engineer-m...,Data Engineer - Manager
1,https://www.builtinnyc.com/job/fp-analyst-data...,FP&A Analyst - Data Insights
2,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
3,https://www.builtinnyc.com/job/data-analyst-do...,"Data Analyst, DOC"
4,https://www.builtinnyc.com/job/data-analyst-qa...,Data Analyst/QA Engineer
5,https://www.builtinnyc.com/job/operations-data...,Operations Data Analyst- Insurance
6,https://www.builtinnyc.com/job/digital-data-an...,Digital Data Analyst
7,https://www.builtinnyc.com/job/marketing-and-c...,Marketing and Customer Data Analyst
8,https://www.builtinnyc.com/job/market-data-ana...,Market Data Analyst
9,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
10,https://www.builtinnyc.com/job/systems-analyst...,Systems Analyst - Data Scientist
11,https://www.builtinnyc.com/job/data-product-an...,"Data Product Analyst, Corporate"
12,https://www.builtinnyc.com/job/analytics-engin...,Analytics Engineer
13,https://www.builtinnyc.com/job/data-engineer-g...,"Data Engineer, Go to Market (Remote)"
14,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer
15,https://www.builtinnyc.com/job/data-protection...,Data Protection Engineer
16,https://www.builtinnyc.com/job/mid-level-data-...,Mid-Level Data Engineer
17,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer
18,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer
19,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer
20,https://www.builtinnyc.com/job/ai-enabled-data...,AI-Enabled Data Engineer
21,https://www.builtinnyc.com/job/data-analyst-qa...,Data Analyst/QA Engineer
22,https://www.builtinnyc.com/job/data-implementa...,Data Implementation Engineer
23,https://www.builtinnyc.com/job/data-migration-...,Data Migration Engineer
24,https://www.builtinnyc.com/job/data-operations...,Data Operations Analyst
25,https://www.builtinnyc.com/job/marketing-data-...,Marketing Data Analyst
26,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
27,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
28,https://www.builtinnyc.com/job/enterprise-mark...,Enterprise Marketing Data Analyst – Cross-Func...
29,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
30,https://www.builtinnyc.com/job/technical-commu...,Technical Communications and Data Analyst
31,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
32,https://www.builtinnyc.com/job/data-analyst-ec...,Data Analyst - Economic Insights & Communications
33,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst
34,https://www.builtinnyc.com/job/legal-assistant...,Legal Assistant / Data Analyst Supporting the ...
35,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst
36,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst
37,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst
38,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst
39,https://www.builtinnyc.com/job/research-data-a...,Research Data Analyst
40,https://www.builtinnyc.com/job/technical-busin...,Technical Business Analyst - User Success & En...
41,https://www.builtinnyc.com/job/data-scientist-...,Data Scientist Analyst - Secondaries & Primaries
42,https://www.builtinnyc.com/job/supplier-data-o...,Supplier Data Operations Analyst
43,https://www.builtinnyc.com/job/investment-quan...,Investment Quant & Data Analyst
44,https://www.builtinnyc.com/job/data-operations...,Data Operations Analyst
45,https://www.builtinnyc.com/job/senior-data-ana...,Senior Data Analyst
46,https://www.builtinnyc.com/job/data-analyst-an...,Data Analyst and Reporting Specialist
47,https://www.builtinnyc.com/job/media-data-anal...,Media Data Analyst
48,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst
49,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst

### Seniority Extraction Helper

In [30]:
def extract_seniority(url: str) -> str:
    try:
        delay = random.uniform(MIN_SCRAPE_DELAY, MAX_SCRAPE_DELAY)
        print(f"  sleeping {delay:.1f}s...")
        time.sleep(delay)
        
        response = requests.get(url, headers=HEADERS, timeout=15)
        print(f"  status: {response.status_code}  html_len: {len(response.text)}")

        if response.status_code != 200:
            return "unavailable"

        if len(response.text) < 50000:
            print("  WARNING: response suspiciously small, likely bot challenge")
            return "unavailable"

        soup = BeautifulSoup(response.text, "html.parser")

        for div in soup.find_all("div", class_=lambda c: c and "align-items-start" in c and "gap-sm" in c):
            if div.find("i", class_=lambda c: c and "fa-trophy" in c):
                span = div.find("span")
                if span:
                    text = span.get_text(strip=True)
                    if text in KNOWN_SENIORITY_VALUES:
                        return text
                    else:
                        print(f"  Unexpected value: {text!r}")
                        return "not_found"

        return "not_found"

    except Exception as e:
        print(f"  Error: {e}")
        return "unavailable"

print("Extractor OK")

Extractor OK

### Gate Check

In [31]:
# confirm unblocked and selector works before touching Snowflake
test_url = candidates.iloc[0]["SOURCE_URL"]
print(f"Gate check: {test_url}\n")

response = requests.get(test_url, headers=HEADERS, timeout=15)
print(f"status: {response.status_code}  html_len: {len(response.text)}")

soup = BeautifulSoup(response.text, "html.parser")
trophy = soup.find("i", class_=lambda c: c and "fa-trophy" in c)
print(f"Trophy found: {trophy is not None}")

if trophy:
    wrapper = trophy.parent.parent
    span = wrapper.find("span")
    print(f"Span text: {span.get_text(strip=True) if span else None}")

print()
if len(response.text) < 50000 or trophy is None:
    print("❌ GATE FAILED — do not proceed. Wait and retry.")
else:
    print("✅ GATE PASSED — safe to continue.")

Gate check: https://www.builtinnyc.com/job/data-engineer-manager/9657210

status: 200  html_len: 87531
Trophy found: True
Span text: Mid level

✅ GATE PASSED — safe to continue.

### Single Row Test

In [32]:
test_url = candidates.iloc[0]["SOURCE_URL"]
test_title = candidates.iloc[0]["TITLE"]

print(f"Testing: {test_title}")
print(f"URL: {test_url}\n")

seniority = extract_seniority(test_url)
print(f"\nExtracted seniority: {seniority!r}")

Testing: Data Engineer - Manager
URL: https://www.builtinnyc.com/job/data-engineer-manager/9657210

  sleeping 8.6s...
  status: 200  html_len: 87531

Extracted seniority: 'Mid level'

In [18]:
response = requests.get(test_url, headers=HEADERS, timeout=15)
print(f"  status: {response.status_code}  html_len: {len(response.text)}")

  status: 200  html_len: 16053

### Write Single Test Row to Snowflake

In [33]:
cur = conn.cursor()
cur.execute("""
    UPDATE RAW.BUILTIN.SRC_POSTINGS
    SET RAW_PAYLOAD = OBJECT_INSERT(RAW_PAYLOAD, 'seniority', %s, true)
    WHERE RAW_PAYLOAD:source_url::STRING = %s
""", (seniority, test_url))
conn.commit()
cur.close()
print(f"Updated 1 row — seniority set to {seniority!r}")

Updated 1 row — seniority set to 'Mid level'

### Verify the Single Test Row

In [34]:
verify = run_query(f"""
    SELECT
        RAW_PAYLOAD:source_url::STRING as source_url,
        RAW_PAYLOAD:crawl_title::STRING as title,
        RAW_PAYLOAD:seniority::STRING as seniority
    FROM RAW.BUILTIN.SRC_POSTINGS
    WHERE RAW_PAYLOAD:source_url::STRING = '{test_url}'
""")
display(verify)

,SOURCE_URL,TITLE,SENIORITY
0,https://www.builtinnyc.com/job/data-engineer-m...,Data Engineer - Manager,Mid level

### Dry Run Remaining Rows (No Wrties)

In [35]:
remaining = candidates[candidates["SOURCE_URL"] != test_url].reset_index(drop=True)

results = []
for i, row in remaining.iterrows():
    print(f"[{i+1}/{len(remaining)}] {row['TITLE'][:50]}")
    seniority = extract_seniority(row["SOURCE_URL"])

    if seniority == "unavailable" and i < 3:
        print("❌ Early unavailable — possible block. Stopping dry run.")
        break

    print(f"  → {seniority!r}")
    results.append({
        "source_url": row["SOURCE_URL"],
        "title": row["TITLE"],
        "seniority": seniority
    })

results_df = pd.DataFrame(results)
print("\nDry run complete")
display(results_df)
print(results_df["seniority"].value_counts())

[1/49] FP&A Analyst - Data Insights
  sleeping 12.6s...
  status: 200  html_len: 89088
  → 'Junior'
[2/49] Data Analyst
  sleeping 13.8s...
  status: 200  html_len: 88155
  → 'Junior'
[3/49] Data Analyst, DOC
  sleeping 8.4s...
  status: 200  html_len: 90746
  → 'Junior'
[4/49] Data Analyst/QA Engineer
  sleeping 14.1s...
  status: 200  html_len: 90109
  → 'Mid level'
[5/49] Operations Data Analyst- Insurance
  sleeping 8.4s...
  status: 200  html_len: 82494
  Unexpected value: 'Senior level'
  → 'not_found'
[6/49] Digital Data Analyst
  sleeping 14.1s...
  status: 200  html_len: 77241
  → 'Junior'
[7/49] Marketing and Customer Data Analyst
  sleeping 12.1s...
  status: 200  html_len: 78066
  → 'Mid level'
[8/49] Market Data Analyst
  sleeping 13.0s...
  status: 200  html_len: 86754
  → 'Entry level'
[9/49] Data Analyst
  sleeping 10.1s...
  status: 200  html_len: 79000
  Unexpected value: 'Senior level'
  → 'not_found'
[10/49] Systems Analyst - Data Scientist
  sleeping 8.5s...
  status: 200  html_len: 86245
  → 'Junior'
[11/49] Data Product Analyst, Corporate
  sleeping 12.2s...
  status: 200  html_len: 87807
  → 'Mid level'
[12/49] Analytics Engineer
  sleeping 12.8s...
  status: 200  html_len: 77269
  → 'Mid level'
[13/49] Data Engineer, Go to Market (Remote)
  sleeping 11.2s...
  status: 200  html_len: 88923
  → 'Mid level'
[14/49] Data Engineer
  sleeping 9.0s...
  status: 200  html_len: 78459
  → 'Mid level'
[15/49] Data Protection Engineer
  sleeping 9.6s...
  status: 200  html_len: 88400
  → 'Mid level'
[16/49] Mid-Level Data Engineer
  sleeping 12.9s...
  status: 200  html_len: 90043
  → 'Mid level'
[17/49] Data Engineer
  sleeping 11.2s...
  status: 200  html_len: 80825
  → 'Entry level'
[18/49] Data Engineer
  sleeping 10.6s...
  status: 200  html_len: 82893
  → 'Junior'
[19/49] Data Engineer
  sleeping 11.7s...
  status: 200  html_len: 75167
  → 'Junior'
[20/49] AI-Enabled Data Engineer
  sleeping 12.5s...
  status: 200  html_len: 81076
  → 'Mid level'
[21/49] Data Analyst/QA Engineer
  sleeping 9.6s...
  status: 200  html_len: 90236
  → 'Mid level'
[22/49] Data Implementation Engineer
  sleeping 11.3s...
  status: 200  html_len: 84148
  → 'Mid level'
[23/49] Data Migration Engineer
  sleeping 10.6s...
  status: 429  html_len: 5983
  → 'unavailable'
[24/49] Data Operations Analyst
  sleeping 10.5s...
  status: 429  html_len: 5983
  → 'unavailable'
[25/49] Marketing Data Analyst
  sleeping 10.3s...
  status: 200  html_len: 82567
  → 'Mid level'
[26/49] Data Analyst
  sleeping 9.3s...
  status: 200  html_len: 96345
  → 'Junior'
[27/49] Data Analyst
  sleeping 8.5s...
  status: 429  html_len: 5928
  → 'unavailable'
[28/49] Enterprise Marketing Data Analyst – Cross-Function
  sleeping 8.5s...
  status: 200  html_len: 91270
  Unexpected value: 'Internship'
  → 'not_found'
[29/49] Data Analyst
  sleeping 9.2s...
  status: 429  html_len: 5928
  → 'unavailable'
[30/49] Technical Communications and Data Analyst
  sleeping 13.3s...
  status: 200  html_len: 90977
  → 'Mid level'
[31/49] Data Analyst
  sleeping 9.6s...
  status: 429  html_len: 5928
  → 'unavailable'
[32/49] Data Analyst - Economic Insights & Communications
  sleeping 11.0s...
  status: 429  html_len: 6070
  → 'unavailable'
[33/49] Data Analyst
  sleeping 9.9s...
  status: 429  html_len: 5928
  → 'unavailable'
[34/49] Legal Assistant / Data Analyst Supporting the US A
  sleeping 14.9s...
  status: 429  html_len: 6136
  → 'unavailable'
[35/49] Data Analyst
  sleeping 14.0s...
  status: 429  html_len: 5928
  → 'unavailable'
[36/49] Data Analyst
  sleeping 13.7s...
  status: 429  html_len: 5928
  → 'unavailable'
[37/49] Data Analyst
  sleeping 13.7s...
  status: 429  html_len: 5928
  → 'unavailable'
[38/49] Data Analyst
  sleeping 11.7s...
  status: 429  html_len: 5928
  → 'unavailable'
[39/49] Research Data Analyst
  sleeping 8.9s...
  status: 429  html_len: 5977
  → 'unavailable'
[40/49] Technical Business Analyst - User Success & Enable
  sleeping 10.4s...
  status: 429  html_len: 6209
  → 'unavailable'
[41/49] Data Scientist Analyst - Secondaries & Primaries
  sleeping 11.8s...
  status: 429  html_len: 6067
  → 'unavailable'
[42/49] Supplier Data Operations Analyst
  sleeping 13.0s...
  status: 429  html_len: 6010
  → 'unavailable'
[43/49] Investment Quant & Data Analyst
  sleeping 8.8s...
  status: 429  html_len: 6001
  → 'unavailable'
[44/49] Data Operations Analyst
  sleeping 9.3s...
  status: 429  html_len: 5983
  → 'unavailable'
[45/49] Senior Data Analyst
  sleeping 13.0s...
  status: 200  html_len: 80313
  → 'Junior'
[46/49] Data Analyst and Reporting Specialist
  sleeping 11.2s...
  status: 429  html_len: 6046
  → 'unavailable'
[47/49] Media Data Analyst
  sleeping 13.6s...
  status: 429  html_len: 5968
  → 'unavailable'
[48/49] Data Analyst
  sleeping 8.6s...
  status: 429  html_len: 5928
  → 'unavailable'
[49/49] Data Analyst
  sleeping 13.2s...
  status: 429  html_len: 5928
  → 'unavailable'

Dry run complete

,source_url,title,seniority
0,https://www.builtinnyc.com/job/fp-analyst-data...,FP&A Analyst - Data Insights,Junior
1,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,Junior
2,https://www.builtinnyc.com/job/data-analyst-do...,"Data Analyst, DOC",Junior
3,https://www.builtinnyc.com/job/data-analyst-qa...,Data Analyst/QA Engineer,Mid level
4,https://www.builtinnyc.com/job/operations-data...,Operations Data Analyst- Insurance,not_found
5,https://www.builtinnyc.com/job/digital-data-an...,Digital Data Analyst,Junior
6,https://www.builtinnyc.com/job/marketing-and-c...,Marketing and Customer Data Analyst,Mid level
7,https://www.builtinnyc.com/job/market-data-ana...,Market Data Analyst,Entry level
8,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,not_found
9,https://www.builtinnyc.com/job/systems-analyst...,Systems Analyst - Data Scientist,Junior
10,https://www.builtinnyc.com/job/data-product-an...,"Data Product Analyst, Corporate",Mid level
11,https://www.builtinnyc.com/job/analytics-engin...,Analytics Engineer,Mid level
12,https://www.builtinnyc.com/job/data-engineer-g...,"Data Engineer, Go to Market (Remote)",Mid level
13,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer,Mid level
14,https://www.builtinnyc.com/job/data-protection...,Data Protection Engineer,Mid level
15,https://www.builtinnyc.com/job/mid-level-data-...,Mid-Level Data Engineer,Mid level
16,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer,Entry level
17,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer,Junior
18,https://www.builtinnyc.com/job/data-engineer/9...,Data Engineer,Junior
19,https://www.builtinnyc.com/job/ai-enabled-data...,AI-Enabled Data Engineer,Mid level
20,https://www.builtinnyc.com/job/data-analyst-qa...,Data Analyst/QA Engineer,Mid level
21,https://www.builtinnyc.com/job/data-implementa...,Data Implementation Engineer,Mid level
22,https://www.builtinnyc.com/job/data-migration-...,Data Migration Engineer,unavailable
23,https://www.builtinnyc.com/job/data-operations...,Data Operations Analyst,unavailable
24,https://www.builtinnyc.com/job/marketing-data-...,Marketing Data Analyst,Mid level
25,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,Junior
26,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,unavailable
27,https://www.builtinnyc.com/job/enterprise-mark...,Enterprise Marketing Data Analyst – Cross-Func...,not_found
28,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,unavailable
29,https://www.builtinnyc.com/job/technical-commu...,Technical Communications and Data Analyst,Mid level
30,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,unavailable
31,https://www.builtinnyc.com/job/data-analyst-ec...,Data Analyst - Economic Insights & Communications,unavailable
32,https://www.builtinnyc.com/job/data-analyst/96...,Data Analyst,unavailable
33,https://www.builtinnyc.com/job/legal-assistant...,Legal Assistant / Data Analyst Supporting the ...,unavailable
34,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable
35,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable
36,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable
37,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable
38,https://www.builtinnyc.com/job/research-data-a...,Research Data Analyst,unavailable
39,https://www.builtinnyc.com/job/technical-busin...,Technical Business Analyst - User Success & En...,unavailable
40,https://www.builtinnyc.com/job/data-scientist-...,Data Scientist Analyst - Secondaries & Primaries,unavailable
41,https://www.builtinnyc.com/job/supplier-data-o...,Supplier Data Operations Analyst,unavailable
42,https://www.builtinnyc.com/job/investment-quan...,Investment Quant & Data Analyst,unavailable
43,https://www.builtinnyc.com/job/data-operations...,Data Operations Analyst,unavailable
44,https://www.builtinnyc.com/job/senior-data-ana...,Senior Data Analyst,Junior
45,https://www.builtinnyc.com/job/data-analyst-an...,Data Analyst and Reporting Specialist,unavailable
46,https://www.builtinnyc.com/job/media-data-anal...,Media Data Analyst,unavailable
47,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable
48,https://www.builtinnyc.com/job/data-analyst/95...,Data Analyst,unavailable

seniority
unavailable    22
Mid level      13
Junior          9
not_found       3
Entry level     2
Name: count, dtype: int64

In [36]:
from IPython.display import HTML

check_df = results_df.copy()
check_df["url"] = check_df["source_url"].apply(lambda x: f'<a href="{x}" target="_blank">{x}</a>')

HTML(check_df[["title", "seniority", "url"]].to_html(render_links=True, escape=False))

In [37]:
from pathlib import Path

CACHE_DIR = Path("./cache")
CACHE_DIR.mkdir(parents=True, exist_ok=True)
BACKFILL_CHECKPOINT = CACHE_DIR / "backfill_results_checkpoint.csv"

results_df.to_csv(BACKFILL_CHECKPOINT, index=False)
print(f"Saved {len(results_df)} rows to {BACKFILL_CHECKPOINT.resolve()}")

Saved 49 rows to /Users/vanbrantley/code/nyc-data-job-market-tracker/ingestion/notebooks/cache/backfill_results_checkpoint.csv

<!-- Got up to 30, 24 and 29 say a seniority but should be not_found. Pulled from Similar Job's seniority. -->

### Bulk Write After Dry Run Looks Good

In [ ]:
# cur = conn.cursor()
# updated = 0
# for _, row in results_df.iterrows():
#     cur.execute("""
#         UPDATE RAW.BUILTIN.SRC_POSTINGS
#         SET RAW_PAYLOAD = OBJECT_INSERT(RAW_PAYLOAD, 'seniority', %s, true)
#         WHERE RAW_PAYLOAD:source_url::STRING = %s
#     """, (row["seniority"], row["source_url"]))
#     updated += 1

# conn.commit()
# cur.close()
# print(f"Updated {updated} rows")

### Final Verification

In [ ]:
# final = run_query("""
#     SELECT
#         RAW_PAYLOAD:seniority::STRING as seniority,
#         COUNT(*) as cnt
#     FROM RAW.BUILTIN.SRC_POSTINGS
#     GROUP BY 1
#     ORDER BY cnt DESC
# """)
# display(final)