### dbt_exploration_2

In [10]:
import os
import pandas as pd
import snowflake.connector
from dotenv import load_dotenv
from IPython.display import display

pd.set_option('display.max_colwidth', 80)
pd.set_option('display.max_rows', 100)

load_dotenv()

conn = snowflake.connector.connect(
    account=os.getenv("SNOWFLAKE_ACCOUNT"),
    user=os.getenv("SNOWFLAKE_USER"),
    password=os.getenv("SNOWFLAKE_PASSWORD"),
    role=os.getenv("SNOWFLAKE_ROLE"),
    warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
    database=os.getenv("SNOWFLAKE_DATABASE"),
)

def run_query(sql: str) -> pd.DataFrame:
    cur = conn.cursor()
    cur.execute(sql)
    rows = cur.fetchall()
    cols = [desc[0] for desc in cur.description]
    cur.close()
    return pd.DataFrame(rows, columns=cols)

print("Connected!")

Connected!

## 1. Raw Table Profiling

For each source table, we:
1. Discover every key present in `RAW_PAYLOAD` dynamically using `OBJECT_KEYS()`
2. Count how often each key is non-null across all rows
3. Pull one representative sample value per key

This tells us the true shape of each source's payload — including fields the docs may not mention.

In [14]:
def profile_raw_source(database: str, schema: str, table: str) -> pd.DataFrame:
    full_table = f"{database}.{schema}.{table}"

    # Pull all payloads into Python as JSON strings
    raw_df = run_query(f"SELECT RAW_PAYLOAD::STRING AS payload FROM {full_table}")
    total_rows = len(raw_df)

    # Parse JSON and discover all keys in Python
    import json
    all_keys = set()
    parsed = []
    for row in raw_df['PAYLOAD']:
        try:
            obj = json.loads(row)
            parsed.append(obj)
            all_keys.update(obj.keys())
        except Exception:
            parsed.append({})

    # For each key: count non-nulls and grab a sample value
    records = []
    for key in sorted(all_keys):
        values = [p.get(key) for p in parsed]
        non_null = [v for v in values if v is not None]
        sample = str(non_null[0])[:120] if non_null else None
        records.append({
            'PAYLOAD_KEY': key,
            'NON_NULL_COUNT': len(non_null),
            'total_rows': total_rows,
            'population_pct': round(len(non_null) / total_rows * 100, 1),
            'SAMPLE_VALUE': sample,
        })

    return (
        pd.DataFrame(records)
        .sort_values('population_pct', ascending=False)
        .reset_index(drop=True)
    )

In [15]:
print('Profiling JSearch raw payload...')
jsearch_profile = profile_raw_source('RAW', 'JSEARCH', 'SRC_POSTINGS')

print(f"Total rows: {jsearch_profile['total_rows'].iloc[0]}")
print(f"Unique payload keys discovered: {len(jsearch_profile)}")
print()
display(jsearch_profile.drop(columns=['total_rows']))

Profiling JSearch raw payload...
Total rows: 136
Unique payload keys discovered: 34

,PAYLOAD_KEY,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,apply_options,136,100.0,[{'apply_link': 'https://www.linkedin.com/jobs/view/data-analyst-new-york-at...
1,job_description,136,100.0,Jobright is a next-generation AI job search platform built to make career na...
2,job_publisher,136,100.0,LinkedIn
3,job_posted_at_timestamp,136,100.0,1779260400
4,job_posted_at_datetime_utc,136,100.0,2026-05-20T07:00:00.000Z
5,job_posted_at,136,100.0,18 hours ago
6,job_location,136,100.0,"New York, NY"
7,job_id,136,100.0,n7ha1uBvkMfQoGz5AAAAAA==
8,job_highlights,136,100.0,{}
9,job_google_link,136,100.0,https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3D...
10,job_employment_types,136,100.0,['FULLTIME']
11,job_is_remote,136,100.0,False
12,job_title,136,100.0,Data Analyst (New York)
13,job_apply_link,136,100.0,https://www.linkedin.com/jobs/view/data-analyst-new-york-at-jobright-ai-4416...
14,employer_name,136,100.0,Jobright.ai
15,job_apply_is_direct,136,100.0,False
16,job_employment_type,135,99.3,Full-time
17,employer_logo,129,94.9,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc11c46XEF7nUag98qauGW...
18,job_latitude,124,91.2,40.7127753
19,job_state,124,91.2,New York
20,job_longitude,124,91.2,-74.0059728
21,job_city,124,91.2,New York
22,job_country,124,91.2,US
23,employer_website,101,74.3,https://jobright.ai
24,job_benefits_strings,63,46.3,"['Dental insurance', 'Paid time off', 'Health insurance']"
25,job_benefits,63,46.3,"['dental_coverage', 'paid_time_off', 'health_insurance']"
26,job_salary_period,41,30.1,YEAR
27,job_salary_string,41,30.1,"74,160–148,320 a year"
28,job_min_salary,39,28.7,74160
29,job_max_salary,39,28.7,148320
30,job_salary,2,1.5,65
31,job_onet_soc,0,0.0,NaN
32,employer_reviews,0,0.0,NaN
33,job_onet_job_zone,0,0.0,NaN

In [16]:
print('Profiling TheirStack raw payload...')
theirstack_profile = profile_raw_source('RAW', 'THEIRSTACK', 'SRC_POSTINGS')

print(f"Total rows: {theirstack_profile['total_rows'].iloc[0]}")
print(f"Unique payload keys discovered: {len(theirstack_profile)}")
print()
display(theirstack_profile.drop(columns=['total_rows']))

Profiling TheirStack raw payload...
Total rows: 18
Unique payload keys discovered: 48

,PAYLOAD_KEY,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,latitude,18,100.0,40.71427
1,id,18,100.0,698550590
2,keyword_slugs,18,100.0,"['job-descriptions', 'sensors-test-measurement', 'reporting-and-disclosure',..."
3,cities,18,100.0,[]
4,location,18,100.0,"New York, NY"
5,locations,18,100.0,"[{'address': None, 'admin1_code': 'NY', 'admin1_name': 'New York', 'admin2_c..."
6,long_location,18,100.0,"New York, NY"
7,longitude,18,100.0,-74.00597
8,manager_roles,18,100.0,[]
9,matching_phrases,18,100.0,[]
10,matching_words,18,100.0,[]
11,normalized_title,18,100.0,
12,remote,18,100.0,False
13,reposted,18,100.0,False
14,seniority,18,100.0,mid_level
15,short_location,18,100.0,"New York, NY"
16,source_url,18,100.0,https://www.linkedin.com/jobs/view/advertising-data-analyst-at-hearst-televi...
17,state_code,18,100.0,NY
18,technology_slugs,18,100.0,"['attribution', 'power-bi']"
19,job_title,18,100.0,Advertising Data Analyst
20,url,18,100.0,https://www.linkedin.com/jobs/view/advertising-data-analyst-at-hearst-televi...
21,hybrid,18,100.0,False
22,countries,18,100.0,[]
23,country_code,18,100.0,US
24,hiring_team,18,100.0,[]
25,continents,18,100.0,[]
26,company_object,18,100.0,"{'alexa_ranking': None, 'annual_revenue_usd': None, 'annual_revenue_usd_read..."
27,country_codes,18,100.0,['US']
28,date_posted,18,100.0,2026-05-31
29,description,18,100.0,**Job Description**\nHearst Television is seeking a Advertising Data Analyst...
30,discovered_at,18,100.0,2026-05-31T11:44:31.532000Z
31,employment_statuses,18,100.0,['full_time']
32,company,18,100.0,Hearst Television
33,has_blurred_data,18,100.0,False
34,country,18,100.0,United States
35,company_domain,15,83.3,hearst.com
36,easy_apply,3,16.7,True
37,salary_string,2,11.1,$145k - $175k per year
38,salary_currency,2,11.1,USD
39,min_annual_salary,2,11.1,145000
40,min_annual_salary_usd,2,11.1,145000
41,max_annual_salary_usd,2,11.1,175000
42,max_annual_salary,2,11.1,175000
43,avg_annual_salary_usd,2,11.1,160000
44,postal_code,1,5.6,10022
45,final_url,1,5.6,https://job-boards.greenhouse.io/whalarinc/jobs/6011264004
46,date_reposted,0,0.0,NaN
47,closed_at,0,0.0,NaN

In [17]:
print('Profiling Built In raw payload...')
builtin_profile = profile_raw_source('RAW', 'BUILTIN', 'SRC_POSTINGS')

print(f"Total rows: {builtin_profile['total_rows'].iloc[0]}")
print(f"Unique payload keys discovered: {len(builtin_profile)}")
print()
display(builtin_profile.drop(columns=['total_rows']))

Profiling Built In raw payload...
Total rows: 18
Unique payload keys discovered: 19

,PAYLOAD_KEY,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,@context,18,100.0,https://schema.org
1,employmentType,18,100.0,FULL_TIME
2,title,18,100.0,Investment Quant & Data Analyst
3,source_url,18,100.0,https://www.builtinnyc.com/job/investment-quant-data-analyst/9550551
4,scraped_at,18,100.0,2026-05-31T18:12:20.445986+00:00
5,industry,18,100.0,"['Fintech', 'Payments', 'Financial Services']"
6,identifier,18,100.0,"{'@type': 'PropertyValue', 'name': 'Resolution Life', 'value': '9550551'}"
7,@type,18,100.0,JobPosting
8,hiringOrganization,18,100.0,"{'@type': 'Organization', 'logo': {'@type': 'ImageObject', 'representativeOf..."
9,directApply,18,100.0,False
10,description,18,100.0,"<p><span>As part of the application process, a candidate account is required..."
11,datePosted,18,100.0,2026-05-29
12,crawl_title,18,100.0,Investment Quant & Data Analyst
13,applicantLocationRequirements,18,100.0,"{'@type': 'Country', 'name': 'USA'}"
14,validThrough,18,100.0,2026-06-28T22:42:02+00:00
15,jobLocation,17,94.4,"{'@type': 'Place', 'address': {'@type': 'PostalAddress', 'addressCountry': '..."
16,jobBenefits,16,88.9,"['Offers 401(K)', 'Offers disability insurance', 'Offers life insurance', 'O..."
17,baseSalary,14,77.8,"{'@type': 'MonetaryAmount', 'currency': 'USD', 'value': {'@type': 'Quantitat..."
18,jobLocationType,6,33.3,TELECOMMUTE

In [18]:
comparison = (
    jsearch_profile[['PAYLOAD_KEY', 'population_pct']].rename(columns={'population_pct': 'jsearch_%'})
    .merge(
        theirstack_profile[['PAYLOAD_KEY', 'population_pct']].rename(columns={'population_pct': 'theirstack_%'}),
        on='PAYLOAD_KEY', how='outer'
    )
    .merge(
        builtin_profile[['PAYLOAD_KEY', 'population_pct']].rename(columns={'population_pct': 'builtin_%'}),
        on='PAYLOAD_KEY', how='outer'
    )
    .fillna(0.0)
    .sort_values('jsearch_%', ascending=False)
    .reset_index(drop=True)
)

print("Field coverage comparison across raw sources (population %)")
display(comparison)

Field coverage comparison across raw sources (population %)

                      PAYLOAD_KEY  jsearch_%  theirstack_%  builtin_%
0            job_employment_types      100.0           0.0        0.0
1                  job_apply_link      100.0           0.0        0.0
2      job_posted_at_datetime_utc      100.0           0.0        0.0
3         job_posted_at_timestamp      100.0           0.0        0.0
4                       job_title      100.0         100.0        0.0
5                 job_description      100.0           0.0        0.0
6                   job_posted_at      100.0           0.0        0.0
7                 job_google_link      100.0           0.0        0.0
8                  job_highlights      100.0           0.0        0.0
9                          job_id      100.0           0.0        0.0
10                  job_is_remote      100.0           0.0        0.0
11                  job_publisher      100.0           0.0        0.0
12                   job_location      100.0           0.0        0.0
13                  apply_options      100.0           0.0        0.0
14                  employer_name      100.0           0.0        0.0
15            job_apply_is_direct      100.0           0.0        0.0
16            job_employment_type       99.3           0.0        0.0
17                  employer_logo       94.9           0.0        0.0
18                    job_country       91.2           0.0        0.0
19                       job_city       91.2           0.0        0.0
20                   job_latitude       91.2           0.0        0.0
21                  job_longitude       91.2           0.0        0.0
22                      job_state       91.2           0.0        0.0
23               employer_website       74.3           0.0        0.0
24                   job_benefits       46.3           0.0        0.0
25           job_benefits_strings       46.3           0.0        0.0
26              job_salary_period       30.1           0.0        0.0
27              job_salary_string       30.1           0.0        0.0
28                 job_max_salary       28.7           0.0        0.0
29                 job_min_salary       28.7           0.0        0.0
30                     job_salary        1.5           0.0        0.0
31                       location        0.0         100.0        0.0
32                    postal_code        0.0           5.6        0.0
33                            url        0.0         100.0        0.0
34                          title        0.0           0.0      100.0
35               technology_slugs        0.0         100.0        0.0
36                     state_code        0.0         100.0        0.0
37                     source_url        0.0         100.0      100.0
38                 short_location        0.0         100.0        0.0
39                      seniority        0.0         100.0        0.0
40                     scraped_at        0.0           0.0      100.0
41                  salary_string        0.0          11.1        0.0
42                salary_currency        0.0          11.1        0.0
43                       reposted        0.0         100.0        0.0
44                         remote        0.0         100.0        0.0
45               normalized_title        0.0         100.0        0.0
46                       latitude        0.0         100.0        0.0
47          min_annual_salary_usd        0.0          11.1        0.0
48              min_annual_salary        0.0          11.1        0.0
49          max_annual_salary_usd        0.0          11.1        0.0
50              max_annual_salary        0.0          11.1        0.0
51                 matching_words        0.0         100.0        0.0
52               matching_phrases        0.0         100.0        0.0
53                  manager_roles        0.0         100.0        0.0
54                      longitude        0.0         100.0        0.0
55                  long_location        0.0         100.0        0.0
56                   job_onet_soc        0.0           0.0        0.0
57                  keyword_slugs        0.0         100.0        0.0
58                      locations        0.0         100.0        0.0
59                       @context        0.0           0.0      100.0
60              job_onet_job_zone        0.0           0.0        0.0
61                     continents        0.0         100.0        0.0
62                    date_posted        0.0         100.0        0.0
63                     datePosted        0.0           0.0      100.0
64                    crawl_title        0.0           0.0      100.0
65                  country_codes        0.0         100.0        0.0
66                   country_code        0.0         100.0        0.0
67                        country        0.0         100.0        0.0
68                      countries        0.0         100.0        0.0
69                 company_object        0.0         100.0        0.0
70                          @type        0.0           0.0      100.0
71                 company_domain        0.0          83.3        0.0
72                        company        0.0         100.0        0.0
73                      closed_at        0.0           0.0        0.0
74                         cities        0.0         100.0        0.0
75                     baseSalary        0.0           0.0       77.8
76          avg_annual_salary_usd        0.0          11.1        0.0
77  applicantLocationRequirements        0.0           0.0      100.0
78                  date_reposted        0.0           0.0        0.0
79                    description        0.0         100.0      100.0
80                    directApply        0.0           0.0      100.0
81                  discovered_at        0.0         100.0        0.0
82                jobLocationType        0.0           0.0       33.3
83                    jobLocation        0.0           0.0       94.4
84                    jobBenefits        0.0           0.0       88.9
85                       industry        0.0           0.0      100.0
86                     identifier        0.0           0.0      100.0
87                             id        0.0         100.0        0.0
88                         hybrid        0.0         100.0        0.0
89                    hiring_team        0.0         100.0        0.0
90             hiringOrganization        0.0           0.0      100.0
91               has_blurred_data        0.0         100.0        0.0
92                      final_url        0.0           5.6        0.0
93            employment_statuses        0.0         100.0        0.0
94                 employmentType        0.0           0.0      100.0
95               employer_reviews        0.0           0.0        0.0
96                     easy_apply        0.0          16.7        0.0
97                   validThrough        0.0           0.0      100.0

## 2. Enrichment Table Profiling

Column-level population rates for `ENRICHED.PUBLIC.JOB_ENRICHMENT` across all records.

This tells us which enrichment fields the LLM is reliably filling vs. leaving null.

In [19]:
# Pull the full enrichment table once — reused for all profiling below
enrichment_df = run_query("SELECT * FROM ENRICHED.PUBLIC.JOB_ENRICHMENT")
print(f"Total enriched records: {len(enrichment_df)}")
print(f"Columns: {enrichment_df.columns.tolist()}")

Total enriched records: 172
Columns: ['JOB_ID', 'SOURCE', 'INFERRED_SENIORITY', 'IS_TITLE_INFLATED', 'INFLATION_REASONING', 'ROLE_ARCHETYPE', 'WORK_FOCUS', 'TECH_STACK_REQUIRED', 'TECH_STACK_PREFERRED', 'PARADIGMS_REQUIRED', 'PARADIGMS_PREFERRED', 'DEGREE_REQUIREMENT', 'YEARS_REQUIRED_MIN', 'YEARS_REQUIRED_MAX', 'SALARY_MIN', 'SALARY_MAX', 'CONFIDENCE_SCORE', 'ENRICHED_AT', 'MODEL_VERSION']

In [20]:
def profile_enrichment_table(df: pd.DataFrame) -> pd.DataFrame:
    total_rows = len(df)
    
    records = []
    for col in df.columns:
        non_null = df[col].notna().sum()
        sample = df[col].dropna().iloc[0] if non_null > 0 else None
        records.append({
            'COLUMN_NAME': col,
            'NON_NULL_COUNT': int(non_null),
            'total_rows': total_rows,
            'population_pct': round(non_null / total_rows * 100, 1),
            'SAMPLE_VALUE': str(sample)[:120] if sample is not None else None,
        })
    
    return pd.DataFrame(records).reset_index(drop=True)


def profile_enrichment_by_source(source_name: str, full_df: pd.DataFrame) -> pd.DataFrame:
    df = full_df[full_df['SOURCE'].str.upper() == source_name.upper()].copy()
    total_rows = len(df)

    skip_cols = {'JOB_ID', 'SOURCE', 'ENRICHED_AT'}
    
    records = []
    for col in df.columns:
        if col in skip_cols:
            continue
        non_null = df[col].notna().sum()
        sample = df[col].dropna().iloc[0] if non_null > 0 else None
        records.append({
            'COLUMN_NAME': col,
            'NON_NULL_COUNT': int(non_null),
            'total_rows': total_rows,
            'population_pct': round(non_null / total_rows * 100, 1),
            'SAMPLE_VALUE': str(sample)[:120] if sample is not None else None,
        })
    
    return pd.DataFrame(records).reset_index(drop=True)

In [21]:
print("Enrichment table — all sources:")
display(profile_enrichment_table(enrichment_df).drop(columns=['total_rows']))

Enrichment table — all sources:

,COLUMN_NAME,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,JOB_ID,172,100.0,9526440
1,SOURCE,172,100.0,builtin
2,INFERRED_SENIORITY,172,100.0,mid
3,IS_TITLE_INFLATED,172,100.0,False
4,INFLATION_REASONING,52,30.2,The title 'Senior Data Analyst' suggests a higher level of experience than t...
5,ROLE_ARCHETYPE,172,100.0,data_analyst
6,WORK_FOCUS,172,100.0,build analytical foundations for media decisions
7,TECH_STACK_REQUIRED,172,100.0,"[\n ""sql"",\n ""snowflake"",\n ""tableau"",\n ""sigma"",\n ""lookers"",\n ""powe..."
8,TECH_STACK_PREFERRED,172,100.0,"[\n ""python"",\n ""r""\n]"
9,PARADIGMS_REQUIRED,172,100.0,"[\n ""data visualization"",\n ""data storytelling"",\n ""data management"",\n ..."
10,PARADIGMS_PREFERRED,172,100.0,"[\n ""analytics processes"",\n ""automation opportunities"",\n ""reporting bes..."
11,DEGREE_REQUIREMENT,172,100.0,none
12,YEARS_REQUIRED_MIN,142,82.6,2.0
13,YEARS_REQUIRED_MAX,80,46.5,4.0
14,SALARY_MIN,97,56.4,75000.0
15,SALARY_MAX,95,55.2,90000.0
16,CONFIDENCE_SCORE,172,100.0,0.9
17,ENRICHED_AT,172,100.0,2026-06-03 22:29:06.921837+00:00
18,MODEL_VERSION,172,100.0,gpt-4o-mini

## 3. Enrichment Quality by Source

The same column-level profiling, but split by source.

Key things to look for:
- **Built In** — expect degraded extraction quality due to raw HTML in descriptions
- **TheirStack** — smaller sample size, watch for systematic nulls
- **JSearch** — largest sample, should be the baseline

In [22]:
source_counts = enrichment_df.groupby('SOURCE').size().reset_index(name='record_count')
print("Enriched record counts by source:")
display(source_counts)

Enriched record counts by source:

                                   SOURCE  record_count
0                                 builtin            18
1  jsearch:Analytics Engineer in New York            60
2        jsearch:Data Analyst in New York            76
3                              theirstack            18

In [24]:
for source in ['jsearch:Analytics Engineer in New York', 'jsearch:Data Analyst in New York', 'theirstack', 'builtin']:
    print(f"\n{'='*50}")
    print(f"{source.upper()} enrichment quality:")
    result = profile_enrichment_by_source(source, enrichment_df)
    print(f"Records: {result['total_rows'].iloc[0]}")
    display(result.drop(columns=['total_rows']))

==================================================
JSEARCH:ANALYTICS ENGINEER IN NEW YORK enrichment quality:
Records: 60

,COLUMN_NAME,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,INFERRED_SENIORITY,60,100.0,senior
1,IS_TITLE_INFLATED,60,100.0,False
2,INFLATION_REASONING,27,45.0,The title 'Senior Software Engineer' implies a higher seniority than the 4 y...
3,ROLE_ARCHETYPE,60,100.0,software_engineer
4,WORK_FOCUS,60,100.0,design and build backend services and apis
5,TECH_STACK_REQUIRED,60,100.0,"[\n ""python"",\n ""sql"",\n ""airflow"",\n ""dbt""\n]"
6,TECH_STACK_PREFERRED,60,100.0,"[\n ""fastapi"",\n ""flask"",\n ""django"",\n ""aws""\n]"
7,PARADIGMS_REQUIRED,60,100.0,"[\n ""data governance"",\n ""data quality""\n]"
8,PARADIGMS_PREFERRED,60,100.0,"[\n ""ci/cd"",\n ""automated testing"",\n ""operational reliability""\n]"
9,DEGREE_REQUIREMENT,60,100.0,none
10,YEARS_REQUIRED_MIN,51,85.0,5.0
11,YEARS_REQUIRED_MAX,25,41.7,7.0
12,SALARY_MIN,32,53.3,160000.0
13,SALARY_MAX,31,51.7,200000.0
14,CONFIDENCE_SCORE,60,100.0,0.9
15,MODEL_VERSION,60,100.0,gpt-4o-mini

==================================================
JSEARCH:DATA ANALYST IN NEW YORK enrichment quality:
Records: 76

,COLUMN_NAME,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,INFERRED_SENIORITY,76,100.0,mid
1,IS_TITLE_INFLATED,76,100.0,False
2,INFLATION_REASONING,24,31.6,The title 'Senior Pricing Analytics Analyst' suggests a higher level of expe...
3,ROLE_ARCHETYPE,76,100.0,data_analyst
4,WORK_FOCUS,76,100.0,analyze performance and drive operational improvements
5,TECH_STACK_REQUIRED,76,100.0,"[\n ""sql""\n]"
6,TECH_STACK_PREFERRED,76,100.0,"[\n ""python""\n]"
7,PARADIGMS_REQUIRED,76,100.0,"[\n ""quantitative analysis"",\n ""data visualization""\n]"
8,PARADIGMS_PREFERRED,76,100.0,"[\n ""dashboarding""\n]"
9,DEGREE_REQUIREMENT,76,100.0,equivalent_ok
10,YEARS_REQUIRED_MIN,65,85.5,3.0
11,YEARS_REQUIRED_MAX,39,51.3,3.0
12,SALARY_MIN,42,55.3,82800.0
13,SALARY_MAX,42,55.3,103500.0
14,CONFIDENCE_SCORE,76,100.0,0.9
15,MODEL_VERSION,76,100.0,gpt-4o-mini

==================================================
THEIRSTACK enrichment quality:
Records: 18

,COLUMN_NAME,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,INFERRED_SENIORITY,18,100.0,mid
1,IS_TITLE_INFLATED,18,100.0,False
2,INFLATION_REASONING,0,0.0,NaN
3,ROLE_ARCHETYPE,18,100.0,data_analyst
4,WORK_FOCUS,18,100.0,"design, develop and maintain oracle database applications"
5,TECH_STACK_REQUIRED,18,100.0,"[\n ""oracle"",\n ""pl/sql"",\n ""sql"",\n ""sql developer"",\n ""toad""\n]"
6,TECH_STACK_PREFERRED,18,100.0,[]
7,PARADIGMS_REQUIRED,18,100.0,"[\n ""agile development"",\n ""database design"",\n ""data modeling"",\n ""perf..."
8,PARADIGMS_PREFERRED,18,100.0,[]
9,DEGREE_REQUIREMENT,18,100.0,none
10,YEARS_REQUIRED_MIN,12,66.7,2.0
11,YEARS_REQUIRED_MAX,9,50.0,5.0
12,SALARY_MIN,9,50.0,75000.0
13,SALARY_MAX,8,44.4,95000.0
14,CONFIDENCE_SCORE,18,100.0,0.85
15,MODEL_VERSION,18,100.0,gpt-4o-mini

==================================================
BUILTIN enrichment quality:
Records: 18

,COLUMN_NAME,NON_NULL_COUNT,population_pct,SAMPLE_VALUE
0,INFERRED_SENIORITY,18,100.0,mid
1,IS_TITLE_INFLATED,18,100.0,False
2,INFLATION_REASONING,1,5.6,The title 'Senior Data Analyst' suggests a higher level of experience than t...
3,ROLE_ARCHETYPE,18,100.0,data_analyst
4,WORK_FOCUS,18,100.0,build analytical foundations for media decisions
5,TECH_STACK_REQUIRED,18,100.0,"[\n ""sql"",\n ""snowflake"",\n ""tableau"",\n ""sigma"",\n ""lookers"",\n ""powe..."
6,TECH_STACK_PREFERRED,18,100.0,"[\n ""python"",\n ""r""\n]"
7,PARADIGMS_REQUIRED,18,100.0,"[\n ""data visualization"",\n ""data storytelling"",\n ""data management"",\n ..."
8,PARADIGMS_PREFERRED,18,100.0,"[\n ""analytics processes"",\n ""automation opportunities"",\n ""reporting bes..."
9,DEGREE_REQUIREMENT,18,100.0,none
10,YEARS_REQUIRED_MIN,14,77.8,2.0
11,YEARS_REQUIRED_MAX,7,38.9,4.0
12,SALARY_MIN,14,77.8,75000.0
13,SALARY_MAX,14,77.8,90000.0
14,CONFIDENCE_SCORE,18,100.0,0.9
15,MODEL_VERSION,18,100.0,gpt-4o-mini

In [25]:
def get_source_pct(source_name: str) -> pd.DataFrame:
    return (
        profile_enrichment_by_source(source_name, enrichment_df)
        [['COLUMN_NAME', 'population_pct']]
        .rename(columns={'population_pct': f'{source_name}_%'})
    )

enrichment_comparison = (
    get_source_pct('jsearch')
    .merge(get_source_pct('theirstack'), on='COLUMN_NAME')
    .merge(get_source_pct('builtin'),    on='COLUMN_NAME')
)

enrichment_comparison['builtin_gap'] = (
    enrichment_comparison[['jsearch_%', 'theirstack_%']].mean(axis=1)
    - enrichment_comparison['builtin_%']
).round(1)

print("Enrichment quality by source — population % per column")
print("(builtin_gap = how far Built In lags behind the JSearch/TheirStack average)")
display(
    enrichment_comparison.sort_values('builtin_gap', ascending=False).reset_index(drop=True)
)

Enrichment quality by source — population % per column
(builtin_gap = how far Built In lags behind the JSearch/TheirStack average)

/var/folders/lc/2rldm7cs08zcbz67h_7qc6vw0000gn/T/ipykernel_72084/978289292.py:35: RuntimeWarning: invalid value encountered in scalar divide
  'population_pct': round(non_null / total_rows * 100, 1),

             COLUMN_NAME  jsearch_%  theirstack_%  builtin_%  builtin_gap
0     YEARS_REQUIRED_MAX        NaN          50.0       38.9         11.1
1     INFERRED_SENIORITY        NaN         100.0      100.0          0.0
2      IS_TITLE_INFLATED        NaN         100.0      100.0          0.0
3         ROLE_ARCHETYPE        NaN         100.0      100.0          0.0
4             WORK_FOCUS        NaN         100.0      100.0          0.0
5    TECH_STACK_REQUIRED        NaN         100.0      100.0          0.0
6   TECH_STACK_PREFERRED        NaN         100.0      100.0          0.0
7     PARADIGMS_REQUIRED        NaN         100.0      100.0          0.0
8    PARADIGMS_PREFERRED        NaN         100.0      100.0          0.0
9     DEGREE_REQUIREMENT        NaN         100.0      100.0          0.0
10      CONFIDENCE_SCORE        NaN         100.0      100.0          0.0
11         MODEL_VERSION        NaN         100.0      100.0          0.0
12   INFLATION_REASONING        NaN           0.0        5.6         -5.6
13    YEARS_REQUIRED_MIN        NaN          66.7       77.8        -11.1
14            SALARY_MIN        NaN          50.0       77.8        -27.8
15            SALARY_MAX        NaN          44.4       77.8        -33.4

## 4. Bonus: Value Distribution Checks

Quick frequency tables for the key categorical enrichment fields — useful for validating
that the LLM is using the expected enum values and not hallucinating novel ones.

In [26]:
categorical_fields = [
    ('INFERRED_SENIORITY', 'Seniority distribution'),
    ('ROLE_ARCHETYPE',     'Role archetype distribution'),
    ('DEGREE_REQUIREMENT', 'Degree requirement distribution'),
    ('IS_TITLE_INFLATED',  'Title inflation flags'),
]

for col, label in categorical_fields:
    if col not in enrichment_df.columns:
        print(f"{label}: column not found, skipping")
        continue
    df = (
        enrichment_df[col]
        .value_counts(dropna=False)
        .rename_axis('value')
        .reset_index(name='count')
    )
    df['pct'] = (df['count'] / df['count'].sum() * 100).round(1)
    print(f"\n{label}:")
    display(df)

Seniority distribution:

    value  count   pct
0     mid     95  55.2
1  senior     48  27.9
2   entry     29  16.9

Role archetype distribution:

                value  count   pct
0        data_analyst     93  54.1
1       data_engineer     29  16.9
2  analytics_engineer     22  12.8
3              hybrid     22  12.8
4   software_engineer      6   3.5

Degree requirement distribution:

           value  count   pct
0      bachelors     80  46.5
1           none     56  32.6
2  equivalent_ok     28  16.3
3        masters      8   4.7

Title inflation flags:

   value  count   pct
0  False    120  69.8
1   True     52  30.2

In [27]:
if 'CONFIDENCE_SCORE' in enrichment_df.columns:
    conf_df = (
        enrichment_df['CONFIDENCE_SCORE']
        .dropna()
        .round(1)
        .value_counts()
        .sort_index()
        .rename_axis('score_bucket')
        .reset_index(name='count')
    )
    print("Confidence score distribution (LLM self-assessment):")
    display(conf_df)

Confidence score distribution (LLM self-assessment):

   score_bucket  count
0           0.5      1
1           0.7      4
2           0.8     47
3           0.9    120

In [28]:
salary_df = (
    enrichment_df
    .groupby('SOURCE')
    .apply(lambda g: pd.Series({
        'total_enriched':   len(g),
        'llm_salary_found': g['SALARY_MIN'].notna().sum(),
        'llm_salary_pct':   round(g['SALARY_MIN'].notna().sum() / len(g) * 100, 1),
    }))
    .reset_index()
)

print("LLM salary extraction rate by source:")
display(salary_df)

LLM salary extraction rate by source:

,SOURCE,total_enriched,llm_salary_found,llm_salary_pct
0,builtin,18.0,14.0,77.8
1,jsearch:Analytics Engineer in New York,60.0,32.0,53.3
2,jsearch:Data Analyst in New York,76.0,42.0,55.3
3,theirstack,18.0,9.0,50.0

In [ ]:
# conn.close()
# print('Connection closed.')